language: android

env:
  global:
    - ADB_INSTALL_TIMEOUT=15

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23

script:
  - ./gradlew test